{% set name = "openfst" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.openfst.org/twiki/pub/FST/FstDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 24fb53b72bb687e3fa8ee96c72a31ff2920d99b980a0a8f61dda426fca6713f0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  # If behaving properly these will have return code 1.
  commands:
    - farinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstcompress --helpshort >/dev/null || [[ $? == 1 ]]
    - fstinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstspecial --helpshort >/dev/null || [[ $? == 1 ]]
    - mpdtcompose --helpshort >/dev/null || [[ $? == 1 ]]
    - pdtcompose --helpshort >/dev/null || [[ $? == 1 ]]

about:
  home: http://openfst.org
  license: Apache-2.0
  license_file: COPYING
  summary: Weighted finite-state transducers
  description: |
    A library for constructing, combining, optimizing, and searching weighted 
    finite-state transducers (FSTs)
  doc_url: http://www.openfst.org/twiki/bin/view/FST/FstQuickTour

extra:
  recipe-maintainers:
    - 183amir
    - kylebgorman
    - mcernak
