{% set version = "1.8.2" %}

package:
  name: openfst
  version: {{ version }}

source:
  url: http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-{{ version }}.tar.gz
  sha256: de987bf3624721c5d5ba321af95751898e4f4bb41c8a36e2d64f0627656d8b42
  patches:
    - osx_arm64_configure.patch  # [build_platform != target_platform]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - gnuconfig   # [unix]

test:
  # If behaving properly these will have return code 1.
  commands:
    - farinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstcompress --helpshort >/dev/null || [[ $? == 1 ]]
    - fstinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstspecial --helpshort >/dev/null || [[ $? == 1 ]]
    - mpdtcompose --helpshort >/dev/null || [[ $? == 1 ]]
    - pdtcompose --helpshort >/dev/null || [[ $? == 1 ]]

about:
  home: http://openfst.org
  license: Apache-2.0
  license_file: COPYING
  summary: Weighted finite-state transducers
  description: |
    A library for constructing, combining, optimizing, and searching weighted 
    finite-state transducers (FSTs)
  doc_url: http://www.openfst.org/twiki/bin/view/FST/FstQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
    - mcernak
