appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DKcvX+HrjMRzNEuwfvCWMeK5khnYAkFoaConrEi8mdJ5mqrRJKLrgWSXT01y6X4jxz4E8H7ddeTA1z3d3dLnkgWfetTbZAtkEWhHaeqikd3YKLb3bgclERdZekOdkm7QC0+KjbKO2gBN+zuwro4DPqft5xWbSMrqR26faWTGoy+2iZ4B/AxcgAjtCsFOAgKiZmZCt5u+3ODl4+isy4skay4KEPtVSLvrgZWtsRcenYZ2QG9OcXsrEcVeCxww4tTeECzkfRWw6M+fe0Bh6fNuy0ZkDBadInoDMyXFz6CRuy/an6V7Z7kZ94bkWO0uJPokn93aOaKjNaUvIWHh7WVGhy18xGvKH7SzwQLTB/aSCS+V0d1IpoqAMCVHDnQ5fIOu0VydCdvwSSvd4OtScRP7YmVvI2z9Ad0GRXGozkbtfX+hYYAa1mBbJpv3HoKxs2sLfQKbifNsc+JvYAP+AQ6pnWHbnKeAtRTVK5rXgQgUAzUp6yy/2lUjYMfLIwOgsat41I3pV5+gKElgAGD7r7Eh50MTyFGj+U2MqpRc03v8eAelbPg9aCQuhZj+Sr0+2D6xdTsipa9zFHB+oSiE2KG40sern1MowVKBafMZT6mcUG2ofaGYySW8IidB1Njp61Yz2CH9mcckHgWwQsIsJ0L8cV/0I5JwXBw+D/KzwbZSN5E=}
